### PR TITLE
[Editorial] Various editorial changes

### PR DESCRIPTION
**Pull request by TannerSteven**

### CODE REVIEW

**Comment by acabal** [comment]
Hi there, thanks for these edits!

Before I can merge, you used `'` (apostrophe) instead of `’` (right single quote) in your updates. Can you change them to RSQ?

Thanks!

**Comment by acabal** [comment]
I'm still seeing some in chapters 3 and 29

**Comment by TannerSteven** [comment]
Haha! Yes, I got pulled away half way through the edits, and absent-mindedly pushed one of them. I'll pop them up in a moment.

**Comment by acabal** [comment]
Excellent, thanks!

**Pull request merged**
