### PR TITLE
Various modernizations, spelling standardizations, typographical fixes, etc.

### PR DESCRIPTION
**Pull request by TannerSteven**
I have a few dozen other things earmarked for editing, not least of which are the hundreds of instances of archaic noun capitalization. I'll make a dent in the list every now and again in this manner, if that's acceptable practice.

### CODE REVIEW

**Comment by acabal** [comment]
Great list! I agree with nearly all of these, except for wrapt and stript, which MW defines as their own words: https://www.merriam-webster.com/dictionary/wrapt

Can you rebase this pull request to knock out the wrapt/stript commits? Then I can merge this.

Do you have a few examples of the archaic capitalization you're referring to?

**Comment by TannerSteven** [comment]
I'll be honest here; I'm not 100% sure on how to do that. I'm just clumsily pushing things through the GitHub desktop client, and that doesn't appear to have any rebasing functionality as yet.

**Comment by TannerSteven** [comment]
As for capitalization, here are a few examples:
"Sperm whale" is capitalised extremely often. Sometimes as "Sperm Whale", and sometimes as "Sperm whale". "While Whale", "Right Whale", "Leviathan", and their variants also show up very often. "Polar" is also in there a few times, while literally dozens of other common nouns show up once or twice, eg. "Men-of-War", "Slave-ships", "Caryatid", "Rhyme", "Gam", "Pirates", etc.

**Comment by acabal** [comment]
On your local branch, do `git rebase -i <commit-before-you-started>`. It will open a text editor. For those two commits change the first letter to `d` for drop then save the file. Then you can probably do `git push -f` to upload those changes to your Github branch. I don't know if that automatically updates this pull request, but if not you can just open a new one.

**Comment by TannerSteven** [comment]
Okay, I think I managed to finagle something workable. Let me know if it looks okay.

**Comment by acabal** [comment]
Great, thanks!

**Pull request merged**
